Issue2
JGCRI/CMIP6 pull request #10
Opened 2019-06-25 14:49 UTC by evanoffPNNL

process in R - process_netcdf.R
process in CDO - process_CDO.txt
compare/graph - compare_R-CDO.R

2019-06-25 18:43 UTC, evanoffPNNL commented
Plot from Objective 3.

![image](https://user-images.githubusercontent.com/50331146/60124380-76a53c00-9757-11e9-8245-dbb86d3c4e29.png)

2019-06-25 23:02 UTC, kdorheim requested changes
This is a good start but we are going to want to clean things up a bit before we merge it. Generally I think that this code needs to be better commented. Also let's do the follwing. 
1.  Rename the PR 
2. Remove the csv, and netcdf files from the repository 
3. Add csv and netcdf to the gitignore file

2019-06-25 23:02 UTC, kdorheim commented on KalynTest.Rproj
> +Version: 1.0
Okay so let's rename this project to something that is more descriptive.

2019-06-25 23:02 UTC, kdorheim commented on compare_R-CDO.R
> +
How about we add a few sentences that comment about what this script does and what the final output is. Especially since you are going to be running scripts on a local machine and on pic it would be helpful to specify what computer your code is meant to run on.

2019-06-25 23:02 UTC, kdorheim commented on compare_R-CDO.R
> +BASE        <- './'                         #Sets the working folder root
Is `BASE` the project location on your local machine? Somewhere on pic?

2019-06-25 23:02 UTC, kdorheim commented on compare_R-CDO.R
> +filepath <- filelist
If you save the path as filepath you could cut down on some code, not a big deal but with more complicated functions/code unnecessary lines of code can make debugging a bit more difficult. 
`filepath <- list.files(BASE, to_process, full.names = TRUE)`

2019-06-25 23:02 UTC, kdorheim commented on compare_R-CDO.R
> +#open file and load in variable to process
What file are you importing? Is this the data that you processed in R or via CDO?

2019-06-25 23:02 UTC, kdorheim commented on compare_R-CDO.R
> +#file 2
Again what file are you importing, is this the data that you processed in R or via CDO?

2019-06-25 23:02 UTC, kdorheim commented on compare_R-CDO.R
> +
Add a few comments about the kind of plot that you are making. 
Can you color the lines by the method? 
Can you add title and labels? 





Add a title, x, and y labels?

2019-06-25 23:02 UTC, kdorheim commented on output/CMIP6_annual_global_average.csv
> +"x"
Let's add year, model, ensemble, and variable columns to the data frame. Also let's avoid saving columns with the name `x`, can you rename it as something more descriptive?

2019-06-25 23:02 UTC, kdorheim commented on process_CDO.txt
> +/share/apps/netcdf/4.3.2/gcc/4.4.7/bin/cdo fldmean tas_Amon_MRI-ESM2-0_ssp245_r1i1p1f1_gn_201501-210012.nc fldmean.nc
Please add some comments at the beginning of the script that describe the what the file is doing / what / why / where you are running it.

2019-06-25 23:02 UTC, kdorheim commented on process_function.R
> +#Import libraries necessary to run code
Please add some comments at the beginning of the script that describe the what the file is doing / what / why / where you are running it.

Also let's change the script name to something that is more descriptive of what is going on.

2019-06-25 23:02 UTC, kdorheim commented on process_function.R
> +BASE        <- './'                         #Sets the working folder root
Either provide the `BASE <- full/path/to/the/dir` or a comment that describing where the script should be run from. 

`BASE_DIR` should be `BASE_DIR <- '.'` since you are using `file.path` latter on you do not need to have the `/`.

2019-06-25 23:02 UTC, kdorheim commented on process_function.R
> +
Why is `filelist` indexed?

2019-06-25 23:02 UTC, kdorheim commented on process_function.R
> +}
you can delete `process_NetCDF ` since it is a function that does not do anything. Also when we write functions let's make sure that we include some description of what the function is doing, what inputs it needs and what is going to be returned.

2019-06-25 23:02 UTC, kdorheim commented on process_function.R
> +#reduce from 51200 grid cells/month to 1 value per month, to 1 value per year
So I see what you are trying to do here with the nested for loop but this doesn't work because of the way that temp is index. Check out the dimensions on `temp` it is a 3d array. So indexing temp by v_cells (`temp[v_cells]`) does not select a single grid cell across all the months and years, in order to do that you would have to do something like `temp[lat, lon, ]`. 

That being said I would avoid using for loops there are better tools to use in R such as the the `apply` family. 

So I would do something like this. 

`apply(X = temp, margin = 3, FUN = mean)` this will return a vector of the global monthly mean. If you add a year column to this data frame which you should be able to extract from the netcdf you should be able to use `dplyr` `group_by` and `summarise` function to get the annual average.

2019-06-25 23:02 UTC, kdorheim commented on process_function.R
> +#output = data.frame(ar)
The final data frame that you save should include a year, model, ensemble, and variable columns.

2019-06-25 23:02 UTC, kdorheim commented on process_netcdf.R
> +#Import libraries necessary to run code
Do we need this script?

2019-06-25 23:02 UTC, kdorheim commented on uncommented.R
> +#Import libraries necessary to run code
Do we need this script? Does it need to be included in our repository?

2019-06-26 12:33 UTC, kdorheim commented
@evanoffPNNL one other thing, let's move the scripts associated with test exercise into their own directory. So that they are not mixed in with the final cmip 6 processing code you are going to start writing after this PR is complete.

2019-07-01 19:31 UTC, evanoffPNNL commented on uncommented.R
> +#Import libraries necessary to run code
No, I changed the branch name and I am working on cleaning up the unnecessary files.

2019-07-01 19:33 UTC, evanoffPNNL commented on process_netcdf.R
> +#Import libraries necessary to run code
This was the script that processed the .NC file in R.

2019-07-08 19:40 UTC, evanoffPNNL commented on compare_R-CDO.R
> +#open file and load in variable to process
Removed this file, redundant.

2019-07-08 19:40 UTC, evanoffPNNL commented on uncommented.R
> +#Import libraries necessary to run code
Removed

2019-07-08 19:40 UTC, evanoffPNNL commented on process_function.R
> +#output = data.frame(ar)
Done!

2019-07-08 19:41 UTC, evanoffPNNL commented on process_netcdf.R
> +#Import libraries necessary to run code
This is the script being used going forward, combined/eliminated some others. (still need to upload my versions though)

2019-07-08 19:41 UTC, evanoffPNNL commented on process_function.R
> +#reduce from 51200 grid cells/month to 1 value per month, to 1 value per year
Used your suggestions and completed this.

2021-06-29 13:36 UTC, closed without merging